#!/bin/bash

docker run -ti --rm \
           -v /home/michael/src:/home/michael/src \
           -p 3000:3000 \
           -p 5858:5858 \
           -p 8080:8080 \
           tuttlem/node4 \
           /bin/bash