#!/bin/bash

docker run --rm -ti              \
       -p 3000:3000              \
       -v $(pwd):/usr/src/app    \
       -w /usr/src/app           \
       --net=host                \
	     tuttlem/meteor            \
       "$@"
