#!/bin/bash

docker run --rm \
       -e DISPLAY=$DISPLAY \
       -v /tmp/.X11-unix:/tmp/.X11-unix \
       -v /dev/snd:/dev/snd --privileged \
       -v $(pwd)/src:/src \
       firstmac/eclipse:latest
