#!/bin/bash

docker run --rm \
           --dns=`getent hosts ns3.firstmac.com.au | awk {'printf $1'}` \
           --dns=`getent hosts ns4.firstmac.com.au | awk {'printf $1'}` \
           -v /tmp/.X11-unix:/tmp/.X11-unix \
           -v /home/michael/src/plans:/opt/plans \
           -e DISPLAY=unix:0.0 \
           tuttlem/jmeter
