#!/bin/bash

docker run -d \
       -p 8888:8888 \
       -v /home/michael/src/scala:/usr/src/app \
       --name activator-ui \
       tuttlem/activator \
       sh -c "activator ui -Dhttp.address=0.0.0.0"