#!/bin/bash

xhost +local:

PGADMIN_RUNNING=$(docker inspect --format="{{ .State.Running }}" pgadmin 2> /dev/null)

if [ $? -eq 1 ]; then

  docker run                                           \
         --name pgadmin                                      \
         -v /home/michael/src/sql:/root/sql                 \
         -v /tmp/.X11-unix:/tmp/.X11-unix                   \
         -e DISPLAY=unix:0.0                                \
         tuttlem/pgadmin

else

  if [ "$PGADMIN_RUNNING" == "false" ]; then
    docker start pgadmin
  fi

fi
