#!/bin/bash

docker run -e VIRTUAL_HOST=icarus.local \
           -v /opt/sinopia/storage:/sinopia/storage \
           -v /opt/sinopia/config.yaml:/sinopia/config.yaml \
           --name sinopia -d -p 4873:4873 rnbwd/sinopia
